### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/rcbc#14]
Improve the error messages. Currently a lot of `stopifnot`s.

**Comment by byapparov** [comment]
Did you ever come across 'c++ error' during the execution. I have this problem on debian (doker FROM debian:testing) but code works fine with the same data on my Mac. 

Do you know what is the best way to handle and report those?

**Comment by dirkschumacher** [comment]
If you have a reproducible example, feel free to add a new issue here.

**Comment by byapparov** [comment]
I have done a bit of changes here: #23 

Not sure if `assert_that` is what you had in mind.

I have done a bit of refactoring to understand what was going on with parameters, hope that also helps.

**Comment by byapparov** [comment]
@dirkschumacher this can be closed now I suppose.
