### ISSUE TITLE
Enable parallel by default --enable-cbc-parallel

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/rcbc#18]
The best way seems to be to download the source and compile it with --enable-cbc-parallel

Otherwise you cannot use multiple threads.

```
wget http://www.coin-or.org/download/source/Cbc/Cbc-2.9.8.tgz
gunzip Cbc-2.9.8.tgz
tar xvf Cbc-2.9.8.tar
cd Cbc-2.9.8
mkdir build
cd build
../configure --enable-cbc-parallel
make install
export PKG_CONFIG_PATH="/path/to/build/lib/pkgconfig";
export LD_LIBRARY_PATH="/path/to/build/lib"
Rscript -e "devtools::install_github('dirkschumacher/rcbc')"
```
see also https://github.com/JuliaOpt/Cbc.jl

**Comment by byapparov** [comment]
@dirkschumacher Why do you think this should be done before the cran release?

* The way we use the package it does not seem to be a problem. We usually need to solve ~200 different problems in one run for which we delegate parallelisation to other tools.

* If someone is blocked by this, it can be sorted out outside of the package by build parameter as you mentioned.

**Comment by dirkschumacher** [comment]
Yes it must be sorted out outside of the package. Recently the `homebrew` formula was updated to enable parallel configuration.
