### ISSUE TITLE
use C api of CBC

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/rcbc#20]
I think it is better to use the C API of CBC. Less overhead, fewer dependencies.

**Comment by byapparov** [comment]
@dirkschumacher I assume when you say C API, you are not referring to this: http://adv-r.had.co.nz/C-interface.html ?

I would not mind trying to change current intergration if I have a bit of guidance on what exactly you have in mind.

**Comment by dirkschumacher** [comment]
@byapparov yes exactly. Maybe `Rcpp` is not really needed. I have used the R C interface before (https://github.com/dirkschumacher/rpicosat/blob/master/src/r_picosat.c) and it is actually really nice - a bit more verbose, but nice. 

I just don't know how well supported the C interface of `cbc` is.

**Comment by byapparov** [comment]
As a user of the package I would remove `CRAN release` from this. 

I am not sure what the impact will be in terms of the code & performance, but from the installation point of view it is a minor overhead.

**Comment by byapparov** [comment]
I had a look around and as CBC is written C++ there is no point to use C interface.

I see that you don't like dependencies, but in this case it is justified.
