### ISSUE TITLE
using rcbc in a shiny app / windows

### ISSUE THREAD

**Issue by cmber** [dirkschumacher/rcbc#27]
I've been working with rcbc under windows 10 for some time now and it works perfectly. I was able to install it using devtools. Now, I would like to test a shiny app I developed that makes use of rcbc. When I try to deploy the app (using RStudio) I got the following error: 

------------------------- ANTICONF ERROR ---------------------------
Configuration failed because cbc was not found. Try installing:
 * deb: coinor-libcbc-dev, coinor-libclp-dev (Debian, Ubuntu, etc)
 * rpm: coin-or-Cbc-devel, coin-or-Clp-devel (Fedora, CentOS, RHEL)
 * brew: coin-or-tools/coinor/cbc (Mac OSX)
If cbc is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a cbc.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'

In general I can understand what the error message is telling but I have no idea how to get rid of it. I would appreciate any ideas. Thanks, Christian.

**Comment by dirkschumacher** [comment]
Those libraries might not be available on your shiny server. Do you host it yourself? If you host it on shinyapps.io, you need to make sure shinyapps has the ubuntu dependencies listed above installed. I think you can request that in an rstudio github repository.
