### ISSUE TITLE
Cannot be installed behind proxy

### ISSUE THREAD

**Issue by shuaiwang88** [dirkschumacher/rcbc#28]
Could you provide a built tar.gz file for installation? 
I noticed that it requires installation of cbc, could you provide steps of manual installation? 
I appreciated.

**Comment by dirkschumacher** [comment]
For windows installation a binary is downloaded from winlibs:
https://github.com/dirkschumacher/rcbc/blob/221967a8a7e03326c0b85f2aeb2df82435ef0216/tools/winlibs.R#L6-L11

Maybe that helps
