### ISSUE TITLE
rcbc.zip or rcbc.tar.gz - How does one install rcbc on Windows 10?

### ISSUE THREAD

**Issue by dcjohnson1963** [dirkschumacher/rcbc#29]
I have copied the file to my computer and attempted to install from the dos command line and from the studio - in both instances R does not like it and appears to require a rcbc.tar.gz file to work.

Please advise.

Best,

David Johnson

**Comment by dirkschumacher** [comment]
I don't have a windows machine. But the package is tested on appveyor for Windows. I am not sure how to help you.

**Comment by dirkschumacher** [comment]
The problem might have been fixed now with the contributions from @jeffreyhanson recently. Feel free to reopen, if the problem still exists in the current version.
