### ISSUE TITLE
Row constraints are not being followed by CBC

### ISSUE THREAD

**Issue by dkang9503** [dirkschumacher/rcbc#30]
Hello,

We are trying to solve a very simple problem through rcbc and have been running into some issues.

This is the problem that we are trying to solve

![image](https://user-images.githubusercontent.com/23044451/63205521-7a787f00-c073-11e9-86a9-48c574ec4a3d.png)

and this is the corresponding code to match that

`rcbc::cbc_solve(
  obj = c(0,0),
  mat = matrix(c(1, 0, 0, 1), ncol = 2, nrow = 2),
  row_ub = c(2,2),
  row_lb = c(2,2),
  is_integer = c(FALSE, FALSE),
  max = FALSE
)`

but the solution returned is c(0,0) and the solver says the result is not optimal, and we were wondering why that was. Thanks so much!

**Comment by dirkschumacher** [comment]
Strange - seems like a bug I guess. Thanks for the report

**Comment by dirkschumacher** [comment]
Yeah it was a bug. I guess we need better test cases
