### ISSUE TITLE
Installation Fails on Mac OS X 10.15, with R 4.0

### ISSUE THREAD

**Issue by snestler** [dirkschumacher/rcbc#35]
Since I often have students who use both Macs and PCs, I have one of each.  Things are find one the Windows size, but having problems when trying to install rcbc on my Mac now and encountering difficulty.  Actually, I'm trying to install ROI.plugin.cbc (which then attempts to install rcbc, which fails).  Has anyone gotten this to work?  I have successfully installed CBC via Homebrew.  Thank you.  Errors shown below:

* installing *source* package ‘rcbc’ ...
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/Cellar/cbc/2.10.3_1/include/cbc/coin -I/usr/local/Cellar/cgl/0.60.2/include/cgl/coin -I/usr/local/Cellar/clp/1.17.3/include/clp/coin -I/usr/local/Cellar/osi/0.108.5/include/osi/coin -I/usr/local/Cellar/coinutils/2.11.3/include/coinutils/coin
Using PKG_LIBS=-L/usr/local/Cellar/cbc/2.10.3_1/lib -L/usr/local/Cellar/cgl/0.60.2/lib -L/usr/local/Cellar/clp/1.17.3/lib -L/usr/local/Cellar/osi/0.108.5/lib -L/usr/local/Cellar/coinutils/2.11.3/lib -lCbcSolver -lCbc -lCgl -lOsiClp -lClpSolver -lClp -lOsi -lCoinUtils -lbz2 -lz -framework Accelerate -lm
'config' variable 'CXXCPP' is deprecated
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because cbc was not found. Try installing:
 * deb: coinor-libcbc-dev, coinor-libclp-dev (Debian, Ubuntu, etc)
 * rpm: coin-or-Cbc-devel, coin-or-Clp-devel (Fedora, CentOS, RHEL)
 * brew: coin-or-tools/coinor/cbc (Mac OSX)
If cbc is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a cbc.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘rcbc’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rcbc’
Error: Failed to install 'rcbc' from GitHub:
  (converted from warning) installation of package ‘/var/folders/xd/dxggcb056s7__z2nxnp28vzc0000gn/T//RtmpqxKQLK/file2323dc3e6c6/rcbc_0.1.0.9001.tar.gz’ had non-zero exit status

**Comment by igoreulaers** [comment]
I have the same exact issue as described above, where the rcbc package fails to install despite CBC having been installed using Homebrew. Is there a solution to this issue?
