### ISSUE TITLE
using newer cbc module

### ISSUE THREAD

**Issue by kohleth** [dirkschumacher/rcbc#36]
hi,

on windows the install code by default downloads cbc v2.9.8. I notice that the the [official release](https://github.com/coin-or/Cbc/releases) is already at 2.10.5. is there anyway to use this newer version?

downloading the module on linux using the code on the readme also only gets v2.9.9.

**Comment by dirkschumacher** [comment]
Should be fixed now thanks to PR #46 and @jeffreyhanson
