### ISSUE TITLE
Make package cross platform

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/rcbc#4]
What is the best way to make the package work on Windows and the other supported CRAN platforms? Ideally we would not need to bundle the cbc code with the package.

**Comment by dirkschumacher** [comment]
@jeroen how would we further setup the packages to a) build it on windows (appveyor; win-builder) and b) use r-hub? Thanks again for your help. This is my first package that uses external dependencies and it is cool to see how that works.

**Comment by jeroen** [comment]
For rhub you need to do a PR to https://github.com/r-hub/sysreqsdb with a file that specifies that maps your `SystemRequirements` to the required package name on each system.

Building on windows it difficult. We probably need to build the libs ourselves and then publish them on https://github.com/rwinlib. Maybe I'll have a look next week when I have time.

**Comment by byapparov** [comment]
Hi, 

I am trying to test the package on Mac. It works fine if installed from Github, but I cannot pass the `Build & Reload` stage if code is loaded in RStudio. 

I get this error:

> installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcbc/libs
> ... 
> ** testing if installed package can be loaded
> Error: package or namespace load failed for ‘rcbc’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object  '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcbc/libs/rcbc.so':

May be you already know how to fix this? 

Thanks
Bulat

**Comment by dirkschumacher** [comment]
I fixed an issue with `Rcpp`. Maybe that solves it. Apart from that I am planning to use the C interface of CBC to remove the `Rcpp` dependency.

**Comment by byapparov** [comment]
It worked, I was able to build and run tests.

Thank you very much for prompt response!

**Comment by byapparov** [comment]
@jeroen @dirkschumacher  just checking if you had any luck with windows binaries for CBC?

This seems to be the only issue that blocks CRAN release.

**Comment by rickyars** [comment]
I would love windows binaries for CBC.

**Comment by jeroen** [comment]
They are already there? Did you try it?

**Comment by byapparov** [comment]
@jeroen so we have this: https://github.com/rwinlib/cbc which is great!

Do we need to do anything else for package to build and also set up an appveyor to build on windows?

**Comment by byapparov** [comment]
Ok, I will just put commit here for reference: https://github.com/dirkschumacher/rcbc/commit/4c6b39d6d298b5355a3a2adf172431510f509d42

**Comment by jeroen** [comment]
Appveyor is already setup. The link is in the top of the readme.

**Comment by byapparov** [comment]
In this case issue should be closed and package can submitted to CRAN??

**Comment by jeroen** [comment]
Well that's up to the maintainer. But you can install it from Github on Windows:

```r
devtools::install_github("dirkschumacher/rcbc")
```

**Comment by byapparov** [comment]
@jeroen That is great, thank you for confirming! 

@dirkschumacher Do you think this issue can be closed now?

**Comment by byapparov** [comment]
@jeroen there is one warning actually if I run `devtools::build_win(version = "R-devel")`:

>  checking whether package 'rcbc' can be installed ... WARNING
> Found the following significant warnings:
>   cpp_cbc_solve.cpp:47:29: warning: ISO C++ forbids variable length array 'argList' [-Wvla]
> See 'd:/RCompile/CRANguest/R-devel/rcbc.Rcheck/00install.out' for details.

I am not an expert on c/c++, is that easy to fix?

**Comment by jeroen** [comment]
Yes he can use a `std::vector<std::string>` instead of a `const char * argList[nArgs]`

**Comment by byapparov** [comment]
I guess this should be noted on CRAN submission as `const char * args` is the type of the `CbcMain1` external function and I don't see how to get round it...

@jeroen thank you!
