### ISSUE TITLE
Automatic readme build creates an Readme.html file

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/rcbc#47]
Seems like the new build jobs create an html version instead of an md version of the readme file. It seems like this will be fixed with #41

**Comment by jeffreyhanson** [comment]
Yeah, sorry about that. I think that PR should address this issue. If it doesn't, I'll look into this more and submit another PR to address this issue.

**Comment by dirkschumacher** [comment]
No problem :)

**Comment by jeffreyhanson** [comment]
It looks like the latest PR fixed this issue - I can't see the `README.html` file in the repo anymore. The `.github/depends.Rds` file still persists though - sorry about that - I'll take care of this in the next PR.
