### ISSUE TITLE
inconsistency in example for cbc_solve()

### ISSUE THREAD

**Issue by bernhard-da** [dirkschumacher/rcbc#53]
hi @dirkschumacher thx for this package, hope that it lands on cran soon.

i just spotted a small inconsistency: in the example for `cbc_solve()`, the mathematical formulation (eqn 1a) in line 172 is
`1 * x + 2 * y + 0.5 * z` while the objective coefficients used in the example (line 184) is `obj = c(1, 2, 3)`

**Comment by dirkschumacher** [comment]
Thanks! Will get fixed with PR #61

**Comment by bernhard-da** [comment]
@dirkschumacher  great, thx!
