### ISSUE TITLE
all(is.finite(mat)) throws an error with a sufficiently large matrix

### ISSUE THREAD

**Issue by mlpeck** [dirkschumacher/rcbc#63]
1. This isn't your responsibility but you probably want to know about it. In `cbc_solve()` the line
```
assert_that(all(is.finite(obj)), all(is.finite(mat)))
```
is throwing a `cannot allocate vector of size...` error for a large enough matrix. I encountered this with a 252367 x 1011738 matrix with 2018936 non-zero elements. This worked and returned correct results from an earlier commit of the package without this line. R versions 4.1.2 and 4.1.3, both Windows and Linux.

2. Just FYI. I think this is perfectly legal under the GPL but I have a package that depends on `rcbc`, and I don't expect many potential users to be able to create their own binaries. Therefore I put one in the releases area of my package with links to the source here and documentation on github.io. The source for my packages is at [github.com/mlpeck/lppuw](https://github.com/mlpeck/lppuw).

`rcbc` was a huge help to me by the way. I had previously used a library called lpsolve, which I think is no longer maintained and in any event was orders of magnitude slower on these problems.

**Comment by jazzynorbi** [comment]
Yes, I just ran into the same issue today. I commented out the line and rebuilt the package using
R CMD build rcbc-master
and
R CMD INSTALL --no-multiarch rcbc_0.1.0.9001.tar.gz
and now I can solve very large problem.

**Comment by dirkschumacher** [comment]
Happy to look at a PR for it
