### ISSUE TITLE
Failing unit test on Ubuntu 14.04

### ISSUE THREAD

**Issue by jeroen** [dirkschumacher/rcbc#9]
Travis [log file](https://travis-ci.org/dirkschumacher/rcbc/jobs/227734083):

```
checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Total iterations:               0
  Time (CPU seconds):             0.00
  Time (Wallclock seconds):       0.00
  
  presolve has value on
  maxSolutions was changed from 9999999 to 23
  logLevel was changed from 1 to 1
  Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00
  
  testthat results ================================================================
  OK: 19 SKIPPED: 0 FAILED: 1
  1. Failure: cbc_solve: handles unbounded problems (@test-cbc-solver.R#71) 
  
  Error: testthat unit tests failed
  Execution haltedchecking compiled code ... NOTE

```

**Comment by jeroen** [comment]
I think you can just remove the `dist: precise` entry from the travis matrix. That system is just too old I guess.

**Comment by dirkschumacher** [comment]
I think so too.

**Comment by jeroen** [comment]
Also we need to review the system requirements because I think now that we cleaned up the headers, perhaps not all of `coinor-libcbc-dev, coinor-libclp-dev, coinor-libcoinutils-dev, coinor-libcgl-dev` are required anymore. You need to decide which part of the coinor API you need exactly.

**Comment by dirkschumacher** [comment]
Ok. For now I am quite happy with the CBC interface. Eventually using the C interface might be better, but for now it's fine I guess. I'll see if I can remove any libraries.
